version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11

  pre_build:
    commands:
      - echo Starting build...

  build:
    commands:
      - echo Running Maven tests...
      - mvn clean install

  post_build:
    commands:
      - echo Build completed!

artifacts:
  files:
    - target/message-util-1.0.jar
