version: 0.2

env:
  variables:
    INPUT_FILE: auth-service/configs/saml.yaml
    S3_BUCKET: ""

phases:
  install:
    runtime-versions:
      nodejs: 20.x
  build:
    commands:
      - ls
      - npm install
      - npm run reporter
      - cd auth-service/utils && mkdir -p nodejs/node_modules/utils
      - pwd
      - cd -
      - cd auth-service/utils && mv index.js package.json logger.js CONSTANTS.js secretManager.js cognito.js db.js lambda.js ses.js nodejs/node_modules/utils
      - cd -
      - cd auth-service/lambda/login && npm install --only=production
      - cd -
      - cd auth-service/lambda/signup && npm install --only=production
      - cd -
      - cd auth-service/lambda/resend_verification_email && npm install --only=production
      - cd -
      - cd auth-service/lambda/forgot_password && npm install --only=production
      - cd -
      - cd auth-service/lambda/custom_authorization && npm install --only=production
      - cd -
      - npm run reporter || true
      - |
        if expr ${CODEBUILD_INITIATOR} : ".*codepipeline/usdev" >/dev/null; then
        aws s3 cp static-code-analysis-report.html  s3://dev-us-operations/static-code-report/common/Omron-Foresight-BE-Common/$(($(date +%s) * 1000)).html || true ; else
        echo "not dev";
        fi
      - |
        if expr ${CODEBUILD_INITIATOR} : ".*codepipeline/usqa" >/dev/null; then
        aws s3 cp static-code-analysis-report.html  s3://qa-us-operations/static-code-report/common/Omron-Foresight-BE-Common/$(($(date +%s) * 1000)).html || true ; else
        echo "not qa";
        fi
      - |
        if expr ${CODEBUILD_INITIATOR} : ".*codepipeline/usstg" >/dev/null; then
        aws s3 cp static-code-analysis-report.html  s3://stg-us-operations/static-code-report/common/Omron-Foresight-BE-Common/$(($(date +%s) * 1000)).html || true ; else
        echo "not stg";
        fi
      - |
        if expr ${CODEBUILD_INITIATOR} : ".*codepipeline/usbeta" >/dev/null; then
        aws s3 cp static-code-analysis-report.html  s3://beta-us-operations/static-code-report/common/Omron-Foresight-BE-Common/$(($(date +%s) * 1000)).html || true ; else
        echo "not beta";
        fi
      - |
        if expr ${CODEBUILD_INITIATOR} : ".*codepipeline/usprd" >/dev/null; then
        aws s3 cp static-code-analysis-report.html  s3://prd-us-operations/static-code-report/common/Omron-Foresight-BE-Common/$(($(date +%s) * 1000)).html || true ; else
        echo "not prd";
        fi
      - ls
      - pwd
      - npm run auth-service-lint
      - chmod +x ./auth-service/test/test_runner.sh ; ./auth-service/test/test_runner.sh ${CODEBUILD_INITIATOR} || exit 1
      - aws cloudformation package --template $INPUT_FILE --s3-bucket $S3_BUCKET --output-template auth-service/configs/post-saml.yaml
artifacts:
  files:
    - auth-service/configs/post-saml.yaml