AWSTemplateFormatVersion: "2010-09-09"
Description: Common resources for application deployed to Lambda
Parameters:
  AppName:
    Type: String
    Description: Name of the application.
    MinLength: "1"
    MaxLength: "100"
Resources:
  CodeBuildTrustRole:
    Description: Creating service role in IAM for AWS CodeBuild
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AppName}-codebuild-role"
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com]
          Action: sts:AssumeRole
      Path: /
  CodeBuildRolePolicy:
    Type: AWS::IAM::Policy
    DependsOn: CodeBuildTrustRole
    Description: Setting IAM policy for the service role for AWS CodeBuild
    Properties:
      PolicyName: CodeBuildRolePolicy
      PolicyDocument:
        Statement:
          - Action:
              - s3:*
            Resource:
              - !Sub "arn:aws:s3:::regionenv*"
              - !Sub "arn:aws:s3:::environment_variable*"
            Effect: Allow
            Effect: Allow
          - Effect: Allow
            Resource:
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/regionenv*"
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/environment_variable*"
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:regionenv*"
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:environment_variable*"
            Action:
              - logs:*
          - Effect: Allow
            Resource:
              - !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*"
            Action:
              - kms:*
          - Effect: Allow
            Resource:
              - !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/*"
            Action:
              - ses:SendEmail
          - Effect: Allow
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/regionenv*"
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/environment_variable*"
            Action:
              - dynamodb:*
          - Effect: Allow
            Resource:
              - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:regionenv*"
              - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:environment_variable*"
              - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:regionenv*"
              - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:environment_variable*"
            Action:
              - lambda:*
          - Action:
              - SNS:SetTopicAttributes
              - SNS:Subscribe
              - SNS:Unsubscribe
              - SNS:SetSubscriptionAttributes
              - SNS:GetTopicAttributes
            Resource:
              - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:regionenv*"
          - Action:
              - sqs:*
            Resource:
              - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:regionenv*"
          - Effect: Allow
            Resource: ["*"]
            Action:
              - "cloudfront:*"
              - "acm:*"
              - "ec2:*"
              - "route53:*"
              - "waf:*"
              - "wafv2:*"
              - "apigateway:*"
              - "kms:*"
          - Effect: Allow
            Resource:
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/regionenv*"
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/environment_variable*"
              - !Sub "arn:aws:iam::${AWS::AccountId}:policy/regionenv*"
              - !Sub "arn:aws:iam::${AWS::AccountId}:policy/environment_variable*"
          - Effect: Allow
            Resource:
              - !Sub "arn:aws:codeartifact:${AWS::Region}:${AWS::AccountId}:domain*"
              - !Sub "arn:aws:codeartifact:${AWS::Region}:${AWS::AccountId}:repository*"
              - !Sub "arn:aws:codeartifact:${AWS::Region}:${AWS::AccountId}:package*"
            Action:
              - codeartifact:*
          - Effect: Allow
            Action: sts:GetServiceBearerToken
            Resource:
              - !Sub "arn:aws:sts::${AWS::AccountId}:assumed-role/*"
            Condition:
                StringEquals:
                   "sts:AWSServiceName": "codeartifact.amazonaws.com"
      Roles: [!Ref CodeBuildTrustRole]
  CodePipelineTrustRole:
    Description: Creating service role in IAM for AWS CodePipeline
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AppName}-codepipeline-role"
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [codepipeline.amazonaws.com]
          Action: sts:AssumeRole
      Path: /
  CodePipelineRolePolicy:
    Type: AWS::IAM::Policy
    DependsOn: CodePipelineTrustRole
    Description: Setting IAM policy for the service role for AWS CodePipeline
    Properties:
      PolicyName: CodePipelineRolePolicy
      PolicyDocument:
        Statement:
        - Action: ["cloudwatch:*", "s3:*", "iam:PassRole","codebuild:*","codestar:*", "codestar-connections:UseConnection"]
          Resource: "*"
          Effect: Allow
      Roles: [!Ref CodePipelineTrustRole]
Outputs:
  CodePipelineRole:
    Description: "Role for code pipeline"
    Value: !GetAtt CodePipelineTrustRole.Arn
  CloudformationDeployRole:
    Description: "Role for cloudformation to deploy with."
    Value: !GetAtt CloudFormationTrustRole.Arn
  CodeBuildRole:
    Description: "Role for code build to build"
    Value: !GetAtt CodeBuildTrustRole.Arn
