variable "vpc_id" {}
variable "cidr_block" {}
variable "public_subnets_ids" {}
variable "private_subnets_ids" {}
variable "additional_tags" {}
variable "nat_gateway_id" {}
variable "internet_gateway_id" {}
variable "environment" {}
variable "non_prd_env" {}
variable "project" {}
variable "non_prd_additional_tags" {}
variable "deployment_region" {}
variable "vpc_project" {}
variable "existing_api_interface_endpoint_id" {}
variable "existing_dynamodb_gateway_endpoint_id" {}
variable "existing_s3_gateway_endpoint_id" {}
variable "security_groups" {}
variable "country_environment" {}
variable "existing_subnet_id" {}