version: 0.0
os: linux
files:
  - source: /
    destination: /data/usprd-vs-static-code-analysis-report
hooks:

  AfterInstall:
    - location: static_code_analysis_report_service/script-report/usprd-vs-static-code-analysis-report-permission.sh
    - location: static_code_analysis_report_service/script-report/usprd-vs-static-code-analysis-report-start-service.sh
      timeout: 3600