version: 0.2
phases:
  pre_build:
    commands:
      - echo Build started on `date`
      - echo $CODEBUILD_INITIATOR
      - echo Installing source NPM dependencies...
      - cd $DATA_DIR &&  npm install

  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code

  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - $DATA_DIR/**/*
    - appspec.yml