name: Testing Self-Hosted Runner

on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Echo Content
        run: |
          echo "Ok"
          sleep 15s
