name: Testing Self-Hosted Runner 2

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: github-actions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'   # or whichever version you need

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Run tests
        run: npm test


